In [57]:
# import numpy
import numpy as np
import random

In [29]:
l1 =  [1, 2, 6]
n1 = np.array(l1, float)

In [9]:
print(l1)
print(n1)
print(type(l1))
print(type(n1))

[1, 2, 6]
[1. 2. 6.]
<class 'list'>
<class 'numpy.ndarray'>


In [16]:
print(len(n1))
print(n1[1:])

print("Array: ")
for i in range(len(n1)):
    print(f"{n1[i]} " , end="")
    
print("\nArray: ")
for el in n1:
    print(f"{el} " , end="")

print("\nArray: ")
for ix, el in enumerate(n1):
    print(f"{el} " , end="")

3
[2. 6.]
Array: 
1.0 2.0 6.0 
Array: 
1.0 2.0 6.0 
Array: 
1.0 2.0 6.0 

In [33]:
print(n1.shape)
print(n1.dtype)

n2 = n1.copy()
#n2 = n1
n2[1] = -15
print(n1)
print(n2)

#n1.tolist()
#n1.tostring()

(3,)
float64
[1. 2. 6.]
[  1. -15.   6.]
<class 'list'>


In [37]:
l2= [[1, 4, 6], [7, 8, 9]]
m1 = np.array(l2, float)

array([[1., 4., 6.],
       [7., 8., 9.]])

In [47]:
print(len(l2))
print(len(m1))
print(m1.shape)

2
2
(2, 3)


In [48]:
print(l2[0][1])
print(m1[0][1])
print(m1[0, 1])

4
4.0
4.0


In [56]:
l3 = [[[1, 2,3], [3, 4, 5]], [[1, 2,3], [3, 4, 5]]]
m2 = np.array(l3, float)
m2.shape
m2[0, 1, 0]

3.0

In [70]:
m3 = np.array(range(12), float)
m4 = m3.reshape((3,4))
m5 = m4.reshape(-1)[3:9]
m6 = np.concatenate((m3, m5))
print(m3)
print(m4)
print(m5)
print(m6)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[3. 4. 5. 6. 7. 8.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.  3.  4.  5.  6.  7.  8.]


In [71]:
m7 = np.arange(5)
m7

array([0, 1, 2, 3, 4])

In [85]:
m8 = np.ones((3,3), float)
m8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [84]:
m9 = np.zeros((3,3), float)
m9

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [87]:
m10 = np.identity(3, float)
m10

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
m11 = m8 + m10
m11

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [92]:
m11 * m10

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [93]:
np.sqrt(m11)

array([[1.41421356, 1.        , 1.        ],
       [1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.41421356]])

In [94]:
m6

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,  3.,
        4.,  5.,  6.,  7.,  8.])

In [96]:
m6.sum()

99.0

In [98]:
m6[1:].prod()

804722688000.0

In [101]:
m6.std()

2.9860788111948193

In [102]:
m6.mean()

5.5

In [103]:
m6.var()

8.916666666666666

In [104]:
print(m6.min())
print(m6.max())

0.0
11.0


In [108]:
m11.sum(axis=0)

array([4., 4., 4.])

In [111]:
m8 == m10

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [112]:
m11 > m10

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [113]:
m11 > 1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [118]:
any((m11 > 1).reshape(-1))

True

In [122]:
all((m11 > 1).reshape(-1))

False

In [123]:
m21 = np.array([[1, 2], [3, 4]])
m21

array([[1, 2],
       [3, 4]])

In [124]:
m22 = np.array([5, 6])
m22

array([5, 6])

In [126]:
m23 = np.dot(m21, m22)
m23

array([17, 39])

In [128]:
p1 = np.roots([1, 2, -3])
p1

array([-3.,  1.])

In [135]:
p2 = np.poly([-4, 2])
p2

array([ 1.,  2., -8.])

In [139]:
np.random.seed(314156)

In [147]:
np.random.rand(12).reshape((3,4))

array([[0.43459162, 0.70516594, 0.37597321, 0.78020066],
       [0.58408091, 0.1113382 , 0.96209412, 0.99808402],
       [0.90218182, 0.72544537, 0.05792986, 0.17481443]])

In [155]:
k1 = np.array(range(10))
np.random.shuffle(k1)
print(k1)

[2 5 6 9 3 8 1 0 4 7]


In [159]:
nn1 = np.random.normal(size=100)
nn1

array([ 0.18818107, -0.65099775,  2.19751022,  1.85262383,  0.11070906,
       -1.29466301,  0.49823207, -0.90221055,  0.31366348, -1.05042145,
        0.66467344,  0.05533751,  0.11107276,  0.67064492,  0.30461809,
        0.18510394, -0.32957131, -1.67835377,  0.67072952, -1.55635313,
        1.11254887, -0.522469  , -0.53108502,  0.31351586,  1.05625238,
       -1.16410548, -1.88394995,  0.92748956, -0.41340725,  0.32458935,
       -0.64319562,  2.15784846,  1.02494081,  1.17889212, -0.57894012,
        0.9965987 , -0.97016344,  0.52040287, -1.02969208, -0.48274167,
       -0.84887653, -0.81932256, -0.71025428,  0.19425463, -0.37495614,
       -0.54949958,  0.32230917,  1.34826266, -0.21576407,  0.17535989,
        0.36300257, -0.27026381,  0.83271837,  0.34697409, -1.23202005,
       -0.88500825, -1.1097576 , -1.07814325,  0.73267338,  1.00105771,
        1.18478291,  0.99292438, -0.2212988 ,  1.53972204, -1.5345087 ,
       -2.03121216, -0.01106765,  1.21318695, -1.01275201,  1.08